using AbioticServerManager.Core.Admin;

namespace AbioticServerManager.Tests.AdminTests;

public class AdminIniModeratorEditorTests
{
    private const string RealAdminIni =
        "; Auto-generated by Abiotic Factor — edit with care\n" +
        "[Moderators]\n" +
        "Moderator=ExampleID1\n" +
        "Moderator=ExampleID2\n" +
        "\n" +
        "[BannedPlayers]\n" +
        "BannedPlayer=ExampleBanID1\n" +
        "BannedPlayer=ExampleBanID2\n";

    [Fact]
    public void Lists_only_moderators_section_ids()
    {
        var mods = AdminIniModeratorEditor.ListModerators(RealAdminIni);

        Assert.Equal(["ExampleID1", "ExampleID2"], mods);
    }

    [Fact]
    public void Add_moderator_inserts_into_existing_section_and_preserves_the_rest()
    {
        var updated = AdminIniModeratorEditor.AddModerator(RealAdminIni, "76561198104903704");

        Assert.True(AdminIniModeratorEditor.IsModerator(updated, "76561198104903704"));
        Assert.Contains("[BannedPlayers]", updated);
        Assert.Contains("BannedPlayer=ExampleBanID1", updated);
        Assert.Contains("Moderator=ExampleID1", updated);
        Assert.Contains("Moderator=76561198104903704", updated);
        // The new id is inside the moderators section.
        var lines = updated.Replace("\r", "").Split('\n');
        var sec = Array.IndexOf(lines, "[Moderators]");
        var ban = Array.IndexOf(lines, "[BannedPlayers]");
        var idx = Array.IndexOf(lines, "Moderator=76561198104903704");
        Assert.True(idx > sec);
        Assert.True(idx < ban);
    }

    [Fact]
    public void Add_moderator_is_idempotent()
    {
        var once = AdminIniModeratorEditor.AddModerator(RealAdminIni, "ABC");
        var twice = AdminIniModeratorEditor.AddModerator(once, "ABC");

        Assert.Equal(once, twice);
        Assert.Single(AdminIniModeratorEditor.ListModerators(twice), m => m == "ABC");
    }

    [Fact]
    public void Add_moderator_creates_section_when_missing_keeping_banned_section()
    {
        const string onlyBans = "[BannedPlayers]\nBannedPlayer=KeepMe\n";

        var updated = AdminIniModeratorEditor.AddModerator(onlyBans, "NEWID");

        Assert.Contains("[Moderators]", updated);
        Assert.True(AdminIniModeratorEditor.IsModerator(updated, "NEWID"));
        Assert.Contains("BannedPlayer=KeepMe", updated);
    }

    [Fact]
    public void Remove_moderator_drops_only_that_id()
    {
        var updated = AdminIniModeratorEditor.RemoveModerator(RealAdminIni, "ExampleID1");

        Assert.False(AdminIniModeratorEditor.IsModerator(updated, "ExampleID1"));
        Assert.True(AdminIniModeratorEditor.IsModerator(updated, "ExampleID2"));
        // The ban section is untouched.
        Assert.Contains("BannedPlayer=ExampleBanID1", updated);
    }

    [Fact]
    public void Remove_moderator_ignores_a_banned_with_the_same_value()
    {
        const string ini = "[Moderators]\nModerator=SHARED\n\n[BannedPlayers]\nBannedPlayer=SHARED\n";

        var updated = AdminIniModeratorEditor.RemoveModerator(ini, "SHARED");

        Assert.False(AdminIniModeratorEditor.IsModerator(updated, "SHARED")); // moderator removed
        Assert.Contains("BannedPlayer=SHARED", updated);                       // ban kept
    }

    [Fact]
    public void Replace_moderators_swaps_only_the_moderator_lines()
    {
        var updated = AdminIniModeratorEditor.ReplaceModerators(
            RealAdminIni,
            ["NEW1", "NEW2"]);

        Assert.Equal(["NEW1", "NEW2"], AdminIniModeratorEditor.ListModerators(updated));
        // Comments preserved.
        Assert.Contains("; Auto-generated by Abiotic Factor — edit with care", updated);
        // Banned section preserved byte-for-byte (still has both example IDs).
        Assert.Contains("BannedPlayer=ExampleBanID1", updated);
        Assert.Contains("BannedPlayer=ExampleBanID2", updated);
    }

    [Fact]
    public void Replace_moderators_keeps_inline_comments_inside_the_section()
    {
        const string ini =
            "[Moderators]\n" +
            "; example placeholder\n" +
            "Moderator=OLD\n" +
            "\n" +
            "[BannedPlayers]\n" +
            "BannedPlayer=KeepMe\n";

        var updated = AdminIniModeratorEditor.ReplaceModerators(ini, ["NEW"]);

        Assert.Contains("; example placeholder", updated);
        Assert.Contains("Moderator=NEW", updated);
        Assert.DoesNotContain("Moderator=OLD", updated);
        Assert.Contains("BannedPlayer=KeepMe", updated);
    }

    [Fact]
    public void Replace_moderators_round_trips_arbitrary_ini_body_for_unrelated_sections()
    {
        // Property-style round-trip: feed in a body with unrelated sections,
        // comments, blank lines, and an existing moderator list; after we
        // replace with the SAME ids back, the file must be byte-identical.
        const string original =
            "; preserve me\n" +
            "\n" +
            "[Moderators]\n" +
            "Moderator=ID1\n" +
            "Moderator=ID2\n" +
            "\n" +
            "[BannedPlayers]\n" +
            "BannedPlayer=B1\n" +
            "\n" +
            "[CustomSection]\n" +
            "Key=Value\n";

        var replaced = AdminIniModeratorEditor.ReplaceModerators(original, ["ID1", "ID2"]);

        Assert.Equal(original.Replace("\r\n", "\n", StringComparison.Ordinal), replaced);
    }
}
